repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.50.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_tflint
    -   id: terraform_docs
