version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/
   - source: /httpd.config/
     destination: /etc/httpd/conf.d/
permissions:
   - object: /var/www/html/
     pattern: "**"
     owner: ec2-user
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root
